# Generated by Django 4.0 on 2021-12-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('program_level', models.CharField(max_length=200)),
                ('program_length', models.CharField(max_length=200)),
                ('application_fees', models.CharField(max_length=200)),
                ('tution_fees', models.CharField(max_length=200)),
                ('cost_of_living', models.CharField(max_length=200)),
            ],
        ),
    ]
