# Generated by Django 4.0 on 2021-12-11 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'Courses'},
        ),
        migrations.AlterModelTable(
            name='courses',
            table='Courses List',
        ),
    ]
