# Generated by Django 4.0 on 2021-12-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_courses_options_alter_courses_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('complete_address', models.CharField(max_length=350)),
            ],
        ),
        migrations.AlterModelOptions(
            name='courses',
            options={},
        ),
        migrations.AlterModelTable(
            name='courses',
            table=None,
        ),
    ]
