# Generated by Django 4.0 on 2021-12-11 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_school_alter_courses_options_alter_courses_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
    ]
