# Generated by Django 4.0 on 2021-12-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_courses_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='minimum_level_of_education',
            field=models.CharField(choices=[('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10'), ('11', 'Grade 11'), ('12', 'Grade 12/High School'), ('13', '1-Year Post Secondary Certificate'), ('14', '2-Year Undergraduate Diploma'), ('15', '3-Year Undergraduate Advanced Diploma'), ('16', '3-Year Bachelors Degree'), ('17', '4-Year Bachelors Degree'), ('18', 'Post-Graduate Diploma/Certificate'), ('19', 'Masters Degree'), ('20', 'Doctoral Degree (PhD, M.D,..)')], max_length=3, null=True),
        ),
    ]
