# Generated by Django 4.0 on 2021-12-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_courses_minimum_duolingo_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='seo_description',
            field=models.CharField(help_text='150 max characters', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='seo_keyword',
            field=models.CharField(help_text='Use comma (,) to add more than one keyword', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='seo_title',
            field=models.CharField(help_text='60 max characters', max_length=60, null=True),
        ),
    ]
