# Generated by Django 4.0 on 2021-12-11 22:41

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_courses_seo_description_courses_seo_keyword_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('middle_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('first_language', models.CharField(max_length=50, null=True)),
                ('country_of_citizenship', models.CharField(default='India', max_length=50, null=True)),
                ('passport_number', models.CharField(max_length=50, null=True)),
                ('passport_expry_date', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50, null=True)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married')], max_length=50, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('zipcode', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(default='India', max_length=100, null=True)),
                ('state', models.CharField(default='Delhi', max_length=100, null=True)),
                ('email_address', models.EmailField(max_length=200, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
            ],
        ),
    ]
