# Generated by Django 4.0 on 2021-12-13 12:30

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='country_of_education',
            field=models.CharField(default='India', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='country_of_grade_10_school',
            field=models.CharField(default='India', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='country_of_grade_12_school',
            field=models.CharField(default='India', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='grade_10_attended_school_from',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='grade_10_attended_school_to',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='grade_10_degree_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='grade_10_primary_language_of_instruction',
            field=models.CharField(default='English', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='grade_10_school_address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='grade_10_school_city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='grade_10_school_state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='grade_10_school_zip_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='grade_12_attended_school_from',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='grade_12_attended_school_to',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='grade_12_degree_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='grade_12_primary_language_of_instruction',
            field=models.CharField(default='English', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='grade_12_school_address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='grade_12_school_city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='grade_12_school_state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='grade_12_school_zip_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='highest_level_of_education',
            field=models.CharField(choices=[('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10'), ('11', 'Grade 11'), ('12', 'Grade 12/High School'), ('13', '1-Year Post Secondary Certificate'), ('14', '2-Year Undergraduate Diploma'), ('15', '3-Year Undergraduate Advanced Diploma'), ('16', '3-Year Bachelors Degree'), ('17', '4-Year Bachelors Degree'), ('18', 'Post-Graduate Diploma/Certificate'), ('19', 'Masters Degree'), ('20', 'Doctoral Degree (PhD, M.D,..)')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='marks',
            field=models.CharField(help_text='Marks are in ( % ) percantage', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='school_name_of_grade_10',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='school_name_of_grade_12',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+91', max_length=128, null=True, region=None),
        ),
    ]
