# Generated by Django 4.0 on 2021-12-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_student_country_of_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='english_test_type',
            field=models.CharField(choices=[("I don't have this", "I don't have this"), ('I will provide this later', 'I will provide this later'), ('IELTS', 'IELTS'), ('TOEFL', 'TOEFL'), ('PTE', 'PTE'), ('Duolingo English Test', 'Duolingo English Test')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='more_details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='refusal_visa_from',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='valid_visa',
            field=models.CharField(choices=[('No', 'No'), ('USA F1 Visa', 'USA F1 Visa'), ('Canadian Study Permit or Visitor Visa', 'Canadian Study Permit or Visitor Visa'), ('UK Student Visa (Tier 4) or Short-Term Study Visa', 'UK Student Visa (Tier 4) or Short-Term Study Visa'), ('Australian Study Visa', 'Australian Study Visa')], max_length=100, null=True),
        ),
    ]
