# Generated by Django 4.0 on 2021-12-17 12:58

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_student_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+91 ', max_length=128, null=True, region=None),
        ),
    ]
