# Generated by Django 4.0.4 on 2022-05-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_student_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
